services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: frontend:latest
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
